# Generated by Django 5.0.2 on 2024-03-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('massege', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Course_Name', models.CharField(max_length=20, null=True)),
                ('usn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50, null=True)),
                ('DOB', models.DateField()),
                ('Branch', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
