# Generated by Django 5.0.2 on 2024-03-24 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_student_gender_alter_student_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Gender',
        ),
    ]
